name: Upload APK to GitHub Release

on:
  push:
    tags:
      - 'v*'  # v로 시작하는 태그를 푸시하면 실행됨

jobs:
  release:
    name: Upload APK to GitHub Releases
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload Existing APK to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
